### ISSUE TITLE
list.gen and mlist handling

### ISSUE THREAD

**Issue by njazz** [uliss/pure-data#105]
<img width="673" alt="Screen Shot 2021-01-13 at 23 07 15" src="https://user-images.githubusercontent.com/3996302/104504847-1bb28e80-55f4-11eb-926e-c2e99b0d81dc.png">
in this case the result stores only final value of the element in the list.gen

**Comment by uliss** [comment]
This happend cause mlist output not Mlist itself, but just pointer to stored Mlist. So it always output the same pointer.
To solve this problem in general: we should add **[data.copy]** object, that makes copy.

RTree generation becames more complex, but I think we could add convenient object for such common case.
<img width="631" alt="Снимок экрана 2021-03-05 в 2 53 11" src="https://user-images.githubusercontent.com/350661/110047061-456b7480-7d5e-11eb-908c-69016a2c8ae6.png">

**Comment by njazz** [comment]
yes, that's what i expected to be the reason for that
in my opinion: it would be great to have an option in [list.gen] and all similar objects - like @copy-data or anything because we don't expect this kind of behaviour for other data types
and probably have [data.copy] too with explanations in our data types description - i think this (object reference) behaviour is quite expected when you know how externals work but may be less predictable for new users
thanks
