### ISSUE TITLE
[midi.file] Midi SMF0 not supported

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#106]
"[midi.file] can't read MIDI file ..."
PureData distribution v2020.12, OSX 10.15.4

**Edit:** it looks like I was using Midi SMF0 , only Midi SMF1 format is supported by the object.

Will it be possible to support both file formats?

**Comment by uliss** [comment]
Did you mean SMF0 - when MIDI file tracks are in a joined state?

Could you attach your problem file?

**Comment by 60-hz** [comment]
The [midi.track] can't read some files, but it looks like it is not related to Midi format...
I found a way to read them in pd by re-exporting them using a simple midi converter utility.
