### ISSUE TITLE
where is the speech.flite objcet installed? 

### ISSUE THREAD

**Issue by smomid** [uliss/pure-data#107]
Hi, 

I installed the Ceammc library on my Mac, OS 10.13.6. I have Pd .51.4

I don't think I can use ceammc right now, because I have so many old patches that have conflict with object names, like gate and gain~. However, there are a lot of cool objects I would like to use. 

One object I am interested in is speech.flite. I can see the helpfile, but I can't see the actual object. is there a way to install just this object in my search path and use that? I would like to do this with some of the other objects too, like some of the filters and synths, which sound incredible by the way. 

Thanks, NIck

**Comment by uliss** [comment]
Hi, Nick!

At this moment ceammc external is a library, it means all objects are bundled into one external. 
You can't use any object (with few exceptions like soundtouch~) without loading the whole library.

But there are a good news: in upcoming release name conflicts can be resolved by explicitly specifying object prefix
for objects like gain~, gate etc. Use **[ceammc/gain~]**, **[ceammc/gate]** together with **[else/gain~]**, **[else/gate]**

**Comment by smomid** [comment]
This is great news. Thank you and I am looking forward to this update!
