### ISSUE TITLE
system.exec and pipe symbol

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#112]
Right now, the pipe « | » symbol cannot be used with [system.exec].
It would be very useful to have this feature if possible.

**Comment by uliss** [comment]
May be it's too low level for Pd, but now `[system.exec]` is a wrapper around **exec*** functions:

https://man7.org/linux/man-pages/man3/exec.3.html

To be short, `exec*` functions run new processes not in the shell, as `system` function does.
It allows to control executable process more precisely than with `system`. For example we can run `top` command, getting it's output to Pd.

Seems that we should have `[system.shell]` object that just runs given command in shell asynchronously and just get return code. Thus we can support pipes and other shell stuff.

Think we could do it in the next release

**Comment by uliss** [comment]
added separate issue: #152 , closing
