### ISSUE TITLE
ui objects update pb

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#114]
Under OSX and Windows,  ui.* objects selection highlight is not updated properly after resize.

1 - create ui.toggle - selection / unselection highlight is ok
2 - resize it
3 - object selection highlight is not updated properly

PureData distribution v2020.12 with Ceammc-0.9.1 library
OSX 10.15.4 / Windows10.

Edit: Seems to be the same as https://github.com/uliss/pure-data/issues/101#issue-783306579

**Comment by uliss** [comment]
Could you check new pre release: https://github.com/uliss/pure-data/releases/tag/v2021.03 ?
For me everything works in this build

**Comment by njazz** [comment]
works in 2021.03, tested on os x 10.12.6

**Comment by 60-hz** [comment]
Yes, it works great in 2021.03.

But [ui.toggle] have a little ceiling time (about 500ms) before being able to be re-triggered.
Double click on tick doesn't work for instance, so it feels that something is waiting.

Sending a bang to ui.toggle fast works perfectly, so It might be something within the mouse interaction and the ui.

**Comment by uliss** [comment]
> Yes, it works great in 2021.03.
> 
> But [ui.toggle] have a little ceiling time (about 500ms) before being able to be re-triggered.
> Double click on tick doesn't work for instance, so it feels that something is waiting.
> 
> Sending a bang to ui.toggle fast works perfectly, so It might be something within the mouse interaction and the ui.

Could you test new build:  https://github.com/uliss/pure-data/releases/tag/v2021.03  (re-uploaded)

**Comment by 60-hz** [comment]
Yes, fixed!
