### ISSUE TITLE
midi.kbd issues

### ISSUE THREAD

**Issue by njazz** [uliss/pure-data#115]
OS X 10.12.6, Pd-ceammc 2021.03, 32 bit float
object doesn't react on first key press. If you hold the key you get repetitive notes

**Comment by 60-hz** [comment]
confirmed, OSX 10.15.4

**Comment by uliss** [comment]
Ok, it seems to be Tcl/Tk issue

**Comment by uliss** [comment]
Seems to be fixed by using Tcl8.6.10
https://github.com/uliss/pure-data/releases/tag/v2021.03

**Comment by 60-hz** [comment]
Working nicely.
