### ISSUE TITLE
ui.bang / ui.button

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#117]
ui.bang should flash only a short amount of time (maybe could be specified like classic bang?), so the object's ui behavior  make the visual closer to data behavior, and a bit different from ui.button.

**Comment by uliss** [comment]
old behavoir: `[ui.bang]` is **on** on mouse-down, and **off** on mouse-up
new behavoir: `[ui.bang]` is **on** on mouse-down and **off** after 100ms or mouse-up, which one is earlier
