### ISSUE TITLE
Tick box property

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#118]
Tick box in property not really visible with pd-vanilla and ceammc 2021.03

![Capture d’écran 2021-03-13 à 01 49 23](https://user-images.githubusercontent.com/5449719/111013068-6b1bfd80-839e-11eb-9285-ab6ddfb38855.png)

**Comment by 60-hz** [comment]
This bug might only occurs with tcl/tk > 8.6.10

**Comment by uliss** [comment]
yes, they changed default theme in 8.6.10, will try to fix

**Comment by sebshader** [comment]
@uliss in 8.6.10 you can still see the checkbox, but not in 8.6.11 it seems
it seems to be a bug in the ttk alt theme

**Comment by sebshader** [comment]
I've opened a bug report in tk https://core.tcl-lang.org/tk/tktview/4c7d935e9736a1046a1da3ddd0d9039eb232c943
