### ISSUE TITLE
clarification of ui.icon error in pd vanilla

### ISSUE THREAD

**Issue by sebshader** [uliss/pure-data#119]
the error message says "[ceammc] [ui.icon] is not compatible with your distribution version: 0.51.4". However this happens (and loading the object will fail) regardless of the tcl/tk version used. What was the bug that originally caused the objects to be disabled? Is it possible it has been fixed by tcl/tk 8.6.11? at the very least it would be nice to be able to patch this in tcl/tk for vanilla and still be able to use the ceammc library distributed in deken. thanks

**Comment by 60-hz** [comment]
@sebshader ui.icon works with this pre-release https://github.com/uliss/pure-data/releases/tag/v2021.03 and pd-0.51-4

But I think your Color-themed Pure data release have tcl/tk 8.6.11, which might hide tick boxes  in all properties from ceammc...

see https://github.com/uliss/pure-data/issues/118#issue-830759712

**Comment by uliss** [comment]
> the error message says "[ceammc] [ui.icon] is not compatible with your distribution version: 0.51.4". However this happens (and loading the object will fail) regardless of the tcl/tk version used. What was the bug that originally caused the objects to be disabled? Is it possible it has been fixed by tcl/tk 8.6.11? at the very least it would be nice to be able to patch this in tcl/tk for vanilla and still be able to use the ceammc library distributed in deken. thanks

Vanilla in previous version used tcl/tk 8.5.*, had no png images support and crashed with ui.icon object. 
Now it uses 8.6.10 and may be just check for tcl version in enough.

**Comment by uliss** [comment]
@sebshader should be fix and work in your Pd-next. 
No pd version check is performed, instead we catch on tcl side PNG image creation error
