### ISSUE TITLE
[print] with String / Data type error

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#120]
Works ok in Pd-ceammc_2021.03 pre-released

Using pd-vanilla 0.51-4, any string to [print] returns a red message:
"consistency check failed: print"

- Using [ui.display] to show the result looks ok
- [string2symbol] works also and print symbols outputs from the object

**Comment by uliss** [comment]
It's not really a bug, but I should fix and clear documentation: ceammc Pd distribution adds data printing support to `[print]` object. But it's not possible when using ceammc external in vanilla.

**Comment by 60-hz** [comment]
Ah, ok I see.
But before version 0.9.2 it was possible to see the print as "[data]" and not an error in vanilla pd.

**Comment by uliss** [comment]
yes, you are right. fixed
