### ISSUE TITLE
[string2list] function

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#122]
To fulfill the set of ceammc functions, it would be handy to be able to convert from string to a list, like [string2symbol] can do for symbol.

Otherwise, we need to convert to symbol in a first step, then, convert to list with an external abstraction (since there is also no symbol2list and list2symbol).

**Comment by uliss** [comment]
As I frequently see, common symbol2list usage is: 
```
[symbol2list]
|
[list trim]
```

so I suggest to use more flexible (from my point of view now) object
`[symbol2any]` it act exactly as Pd does: parse input string to sequence of atoms.

and the use case will be
```
[SYMBOL ENTRY]
|
[symbol2any]
|
[some_object] or [list]
```

If I missed something, please, write

**Comment by 60-hz** [comment]
`so I suggest to use more flexible (from my point of view now) object [symbol2any]`
Great, I think I missed it ;) I wonder why it is not listed on my autocomplete plugin...

In my user case I wanted to extract the string from [system.exec] as a list, so I use for example :

![string2list](https://user-images.githubusercontent.com/5449719/113042362-64152d80-919b-11eb-932c-eb17c6b6360a.png)


Is it the correct way to do it?

Also I wonder if [string] act as a [any2string]... why there is no [string2any]. The extra symbol conversion is a bit useless isn't it? Or I miss something :)

**Comment by uliss** [comment]
@60-hz 
sorry, missed your question
string support added to ``[symbol2any]`` and alias ``[string2any]`` added

![Снимок экрана 2021-10-29 в 20 54 44](https://user-images.githubusercontent.com/350661/139481136-8f5ad04a-b3b9-4361-9346-9049ce1ef464.png)
