### ISSUE TITLE
[array.play~] error messages

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#125]
"[array.play~] already playing" message is flooding the console when playing files if the previous haven't reach the end.

I think this message shouldn't appear because the user might want to cut the sound and this is not an error.

Also sometimes when I load many different files, I am receiving:
 [array.play~] [@cursor_samp] value is too big (14272.0), clipping to max: 11591

But I never sent @cursor_samp

**Comment by uliss** [comment]
As I see at this moment the best solution seems to separate **play** command from **setting position** commands.

This allow us to play specified range this way `[@begin 1000, @end 2000, play(`, first we set range, then we play.
If we  want to change play position "on the fly" we can set it with `[@cursor_phase 0.5(` (also `@cursor_samp`) while playing.

So `[play(` should not change/set/reset play range/position. And though sending `play` mesage while playing is not a real error, it doesnt make much sense. May be it's better to output debug warning at log level 3 or 4.

If you prefer common Pd semantics - you could use `[bang(`, it resets play position to the `@begin` position, then starts playing.

The first thing I would like to update: make work `[array.play~]` with `[ui.aview]` out of box, it should accept all output messages from ui.aview: `@cursor_ms`, `@cursor_sec`, `@select_*` etc.

Ths issue with **@cursor_samp** will be fixed: on new file load it will reset all playing positions. The question is - should we stop playing on this case? I think no, loaded file should be played from the beginning.

**Comment by 60-hz** [comment]
`you could use [bang(, it resets play position to the @begin position, then starts playing.`
So simple, and it's ok for my need, thanks.

`May be it's better to output debug warning at log level 3 or 4.`
yes, sounds perfect this way.

`make work [array.play~] with [ui.aview] out of box`
Sounds cool!

`I think no, loaded file should be played from the beginning.`
It's a user preference behavior... but I agree with you. Loading can be considered as a separated process from "play", and the user might be able to stop the file right after loading if he wants to.
