### ISSUE TITLE
random improvement

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#126]
[random.i] / [random.f] etc could have 2 inlets to set the min and max directly like the classic random, which is useful.

Also a [random.list] object with same behavior could be added with and third argument, for list length of random values.

**Comment by uliss** [comment]
``[gen N(`` method added for list generation

![Снимок экрана 2021-10-29 в 22 25 49](https://user-images.githubusercontent.com/350661/139491299-8a44e882-5c2f-4fa2-bcb8-35eaedbf73ce.png)
