### ISSUE TITLE
lyonpotpouri / fftease are outdated

### ISSUE THREAD

**Issue by porres** [uliss/pure-data#127]
these are now available via deken, so maybe there's no need to distribute them, huh?

**Comment by uliss** [comment]
Seems that double versions are not available via deken

**Comment by porres** [comment]
In this case, you can maybe open an issue, collaborate upstream so we can have this available upstream and via deken.

**Comment by porres** [comment]
just opened an issue on FFTease repo, please participate, thanks

**Comment by porres** [comment]
Well, just tried your double precision Pd and the provided fftease doesn't seem to work

**Comment by porres** [comment]
Well, just tried your double precision Pd and the provided fftease doesn't seem to work
<img width="442" alt="Screen Shot 2021-03-31 at 21 55 51" src="https://user-images.githubusercontent.com/5360142/113228820-246a4680-926c-11eb-97f5-d14f7ebf0ce9.png">

**Comment by uliss** [comment]
FFTease and LyonPotpourri now are not build by default.

One can force building with following cmake options:
``cmake -DWITH_EXT_FFTEASE=ON -DWITH_EXT_LYONPOTPOURRI=ON``
