### ISSUE TITLE
[snd.file] get channel number

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#129]
I didn't find a way to get the number of channel with [snd.file] (no property for that?)
`[prop.get] property '@channel' not found in object [snd.file]`
[snd.file] could follow the [soundfiler] and show a second inlet to get info as a list: samplerate, headersize, num channels, bytespersample, & endianness.

**Comment by uliss** [comment]
Now if you need just an information you can set **@verbose** property  to 1.
The format details will dumped to Pd console after loading.

```
[snd.file @verbose 1]
```

But if you want to get them as properties - it's impossible at this moment. Will try to do on next release.

**Comment by 60-hz** [comment]
Great, thanks for the infos!
