### ISSUE TITLE
puredara.info

### ISSUE THREAD

**Issue by porres** [uliss/pure-data#130]
why don't you guys put this in puredata.info? Have it as one of the featured downloads?

**Comment by njazz** [comment]
hello,

and who manages the website (or exactly this section), how can we do that?

**Comment by porres** [comment]
> who manages the website (or exactly this section), how can we do that?

anyone can setup an account and start editing any page ;)

**Comment by uliss** [comment]
added to puredata.info downloads:
http://puredata.info/downloads/ceammc

seems that adding to featured downloads is admin decision

**Comment by porres** [comment]
> seems that adding to featured downloads is admin decision

it is and I'm asking him in https://github.com/pure-data/pddp/issues/34

**Comment by porres** [comment]
> it is and I'm asking him in pure-data/pddp#34

you've been marked in that issue, apparently you have to request it to the admin over there so he knows you actually want this :)  well, do you?
