### ISSUE TITLE
[env.adsr~] not closing

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#131]
[env.adsr~]  should close his gate when receiving @gate 0 but is not if receiving  @gate 0 before adsr Time, resulting in a continuous sound.

ceammc v0.9.3

**Comment by uliss** [comment]
@60-hz 
Would you provide minimal example?
Can't reproduce

**Comment by uliss** [comment]
<img width="318" alt="Снимок экрана 2023-10-22 в 16 34 05" src="https://github.com/uliss/pd-ceammc/assets/350661/76fdcfce-5ffd-4f5f-a7d6-a8b78c48d95e">

Can't reproduce in this example, so closing. 
@60-hz if you will have some more information, please feel free to reopen.
