### ISSUE TITLE
[string.split] output ambiguity

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#133]
[string.split] output is [data] but [ui.display] say : list
Shouldn't it be String? If it is list, then I cannot parse it contents with unpack (type mismatch), so it is quiet ambigous.

![string split](https://user-images.githubusercontent.com/5449719/120664066-e87d7880-c48a-11eb-9425-2ce6e064f62b.png)

**Comment by uliss** [comment]
``@sym`` property flag added to split to list of Pd symbols

![Снимок экрана 2021-10-29 в 22 53 19](https://user-images.githubusercontent.com/350661/139494251-d2bc211c-2d5f-4290-849f-1abae549a350.png)
