### ISSUE TITLE
mouse pointer

### ISSUE THREAD

**Issue by oliverstotz** [uliss/pure-data#134]
hi, 

first, ceammc is an absolutely amazing library ! congrats for everything !

here's my little issue, more a feature request:
i would like to set/change the cursor pointer image when hovering over a ceammc GUI. the big arrow that i see now feeld strange and counterintuitive for me. for me personally it wouldn't need to change at all

**Comment by 60-hz** [comment]
Hi,
You might need to tell which system you are seeing a big arrow. Under OSX the cursor switch to a simple straight arrow that is ok to tell the user that the hovered object is an interactive object.

**Comment by oliverstotz** [comment]
Hi, sorry, my bad ! It's on a Windows 7 / 64 bit machine. PD 0.54-1 (64bit), ceammc 0.9.3.

i added a screenshot which shows the cursor image. best

Oliver

![Clipboard02](https://user-images.githubusercontent.com/19552265/121680974-804a1a80-caba-11eb-979a-39ce064c753d.jpg)
