### ISSUE TITLE
ui.number - up/down arrow keys ? ...

### ISSUE THREAD

**Issue by oliverstotz** [uliss/pure-data#135]
Hi,

again, fantastic library, just beginning to check it out ...

Would it be possible to add support for up/down keys to the ui.number-box ? 
i.e. to raise/lower an integer value by pressing up/down, when the box is selected ?
(like the MAX int-number box)

best

oliver

**Comment by uliss** [comment]
Now you can increment/decrement value by pressing '+' or '-' key
In next release Up/Down keys will be supported

**Comment by uliss** [comment]
available in upcoming release, closing
