### ISSUE TITLE
[hw.arduino] help typo

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#145]
Small typo, the readonly properties should have a "?" in hw.arduino-help.pd :

@connected?
@devices?
@port?

**Comment by uliss** [comment]
@60-hz this not a typo.

The idea of ceammc properties in Pd is the ability to set/get inner object state via messages / special objects.

The message ``[@propA ABC(`` sets property **``@propA``** to ABC
The message ``[@propA?(`` asks property **``@propA``** from object and it outputs it as message ``[@propA XXX(`` to first outlet. 
To separate property requests from main data flow there is a object ``[prop->]``

![Снимок экрана 2021-11-01 в 17 18 40](https://user-images.githubusercontent.com/350661/139686428-7adf41e5-62d7-4458-8903-ada683bc70ea.png)

Also you can get all object properties by sending ``[@*?(`` message.

![Снимок экрана 2021-11-01 в 17 18 09](https://user-images.githubusercontent.com/350661/139686531-97205970-d642-49f5-99d0-dcfaa0e1998f.png)

The only problem with requests occurred when we introduces **flow.*** objects. They should process
all received message without accepting them as property requests. So the other way of setting properties was introduced using internal Pd stuff: using ``[prop.set]`` and ``[prop.get]`` objects. 
When you are using **flow.*** objects it's the only way to get/set properties. With most other object you can use both methods.

![Снимок экрана 2021-11-01 в 17 32 43](https://user-images.githubusercontent.com/350661/139688425-0f1221dc-3697-46c8-bfb8-65c5e9a262da.png)

**Comment by 60-hz** [comment]
Ok, thanks for the clarification. Actually I re-discover the props family of objects in my puredata because I temporary removed them for my workshop menu in order not to overwhelm my students with too much informations.
They could be very useful, but a bit too many objects maybe... still need to understand all the logic.

Note:
- [obj.info] has no help, but could be the same as [prop.get] without arguments?
- Also [obj.info] and [obj.props] reverse the [prop.get] outlets because it extract object from its right outlet, as prop.get and set use the left outlet. It's breaking the logic somehow.
- I don"t fully understand what to do with [obj.props] properties output

**Comment by uliss** [comment]
[obj.info] and [obj.props] supposed to be kind of introspection for ceammc Pd objects, using for live-patching etc. but they are still experimental objects.

1. [obj.info] should me more powerful then [prop.get] because it get information about inlets/outlets and methods
1. [obj.props] probably will be deprecated and [prop.get] should be used instead
1. now just iterating but hope we'll do something like auto-UI abstractions generation etc.

**Comment by uliss** [comment]
Close and add special issue #149
