### ISSUE TITLE
[canvas.dir] broken in a subpatch

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#146]
[canvas.dir] return only "symbol" when inside a subpatch.

OSX 10.15.4 pd-0.51-4 and ceammc v0.9.3

Would be nice also to be able to get differnt patch level from the object like:
[canvas.dir 1] in abstraction will get the main patch's path

**Comment by uliss** [comment]
added **<span>@</span>abs** property for controlling behavior under abstractions, same as for **[canvas.top]**
