### ISSUE TITLE
Pre-release OSX errors

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#153]
I have troubles running the pre-release of ceammc lib with pd-0.51.4 or pd-ceammc distribution under OSX 10.15.4:

`/Users/username/Documents/Pd/externals/ceammc/ceammc.d_amd64: dlopen(/Users/username/Documents/Pd/externals/ceammc/ceammc.d_amd64, 10): Library not loaded: /usr/local/opt/fftw/lib/libfftw3f.3.dylib
  Referenced from: /Users/username/Documents/Pd/externals/ceammc/ceammc.d_amd64
  Reason: image not found
/Users/username/Documents/Pd/externals/ceammc/ceammc.d_amd64: dlopen(/Users/username/Documents/Pd/externals/ceammc/ceammc.d_amd64, 10): Library not loaded: /usr/local/opt/fftw/lib/libfftw3f.3.dylib
  Referenced from: /Users/username/Documents/Pd/externals/ceammc/ceammc.d_amd64
  Reason: image not found`

**Comment by uliss** [comment]
could you try again now?

**Comment by 60-hz** [comment]
It's fixed! Tried with:
ceammc-0.9.4-macosx-10.13-pd-0.51.4-f32.tar.gz 
Pd-ceammc_2021.04-macosx-10.13.zip

**Comment by uliss** [comment]
@60-hz some of your report fixed, could you download and check that everything is ok?
I'm preparing for final release

Thank you

**Comment by 60-hz** [comment]
@uliss Yes, it looks ok with the last release.
