### ISSUE TITLE
rename the repository to "pd-ceammc"?

### ISSUE THREAD

**Issue by umlaeute** [uliss/pure-data#159]
it's probably minor, but whenever i see a repository named "pure-data" that is a fork of "pure-data/pure-data" i wouldn't expect it to get a life of it's own (instead i would expect it to be a working repository to try things out and eventually create PRs).

in order to avoid confusion, i would suggest to rename this repository to `pd-ceammc` (or something else that distinguishes it from the *normal* "pure data")  in the [Settings](https://github.com/uliss/pure-data/settings) - GitHub obviously does a good job and keeps the old name around so no links will break and everything keeps working. but whenever you browse the page, you are redirected to the new URL.

cf. by `test` repository that i just renamed to `testing`: https://github.com/umlaeute/test

**Comment by uliss** [comment]
done
