### ISSUE TITLE
please consider editing your help entries and just change to https://puredata.info/docs

### ISSUE THREAD

**Issue by porres** [uliss/pure-data#162]
I see you have 2 links for books in your help browser.

Floss manuals link is broken, by the way, but it is a Pd-extended Manual, not Pd-Vanilla, neither Pd-ceammc. I was one of the authors in the credits, back in the day. This book is from 2008/2009, verry very outdated. Not sure if it is worth highliting as a source of "help".

maybe you shouldd just refer to https://puredata.info/docs instead, which has a more complete set of online documentation, including the "books about Pd" entry, where one ccan find a working link to Floss Manuals and other books, including kriedler's book, which is also quite old, superficial, and based on pd-extended externals. Note that they are not to reflecct Pd's main sources on documentation... 

Please consider just providing a link to puredata.info and we take care of organizing the information  there and keep the links alive.

**Comment by uliss** [comment]
Floss and Kreidler links will be removed in upcoming release
