### ISSUE TITLE
hoa: missing files

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#164]
Tried under Windows10 and OSX: some files are missing like [hoa.thisprocess~ -1] in the ceammc 0.9.4

**Comment by uliss** [comment]
Yes, hoa help files need to be updated for ceammc

**Comment by uliss** [comment]
<img width="1178" alt="Снимок экрана 2023-10-22 в 15 26 36" src="https://github.com/uliss/pd-ceammc/assets/350661/c71c919a-0d05-4a38-abab-18e67136d330">
Full original HOA documentation added in the latest release.

To see it: open "standard" **hoa.*** object documentation and follow by the link *CICM Documentation*

<img width="1283" alt="Снимок экрана 2023-10-22 в 16 20 42" src="https://github.com/uliss/pd-ceammc/assets/350661/9d92e790-11aa-4d0e-863b-861ea1fe3c9b">
