### ISSUE TITLE
[canvas.top]  issue in abstractions

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#165]
When [canvas.top] is inside abstraction, the width height, or x  y positions return 0.
The objet behave normally in a subpatch.

For those type of objets that get informations from different canvas level (like [system.cursor] or [canvas.dir]) it might be interesting to give the level of the canvas as argument to get information from, rather than making different objects  interface [.current .top...).

**Comment by uliss** [comment]
<img width="548" alt="Снимок экрана 2023-10-22 в 16 17 37" src="https://github.com/uliss/pd-ceammc/assets/350661/ef1f12b6-2e75-46dc-a8b6-3397536cc88d">

added **<span>@</span>abs** property for controlling behavior inside abstractions
