### ISSUE TITLE
CEAMMC library doesn't work; "module could not be found" even though file exists

### ISSUE THREAD

**Issue by flarn2006** [uliss/pure-data#168]
When I start Pure Data, I get this in the log window:

```
[completion-plugin] version 0.47.1
[completion-plugin] loaded 2275 completions in 76 milliseconds
C:\Program Files\PureData CEAMMC (double)\extra\ceammc\ceammc.m_amd64: couldn't load - The specified module could not be found.

C:\Program Files\PureData CEAMMC (double)\extra\ceammc\ceammc.m_amd64: couldn't load - The specified module could not be found.

ceammc: can't load library
```

And none of the CEAMMC stuff works. I checked the path that was listed and the file does in fact exist. I tried both the double and float versions and neither one works.

**Comment by kgetech** [comment]
I am having the same error. After exploring the events with ProcMon64 from the Microsoft SysInternals suite, this is what I could find. I hope it helps to determine the issue. 

![image](https://user-images.githubusercontent.com/8975739/174204537-c22cdb67-5a21-4318-baa8-f4aab828738d.png)
![image](https://user-images.githubusercontent.com/8975739/174204658-185757bf-bff3-45c3-a860-9b573bdeb83a.png)

**Comment by kgetech** [comment]
I decided to try and load a ceammc module an.onset, and this is what Procmon spit out:
![image](https://user-images.githubusercontent.com/8975739/174206556-52302da0-07d0-4ab6-b6f6-40a869fdaa53.png)
While the ceammc.m_amd64 file *DOES* exist (added this notation to clarify that I was experiencing the same issue), when it looks for other parts to the ceammc lib, they don't exist in the file structure, searching through the program install directory only returned:
D:\PureDataCEAMMC\extra\ceammc\an.onset~-help.pd
D:\PureDataCEAMMC\extra\ceammc\an.onset-help.pd

**Comment by kgetech** [comment]
I discovered the problem on my end. 

Norton 360 was removing all of those files as medium-risk files.

To solve the problem:
1. Norton 360 > Settings > Antivirus > Scans and Risks > Exclusions/Low Risks > Items to Exclude From Scans > Configure [+] > [Add installation Directory]
2. Norton 360 > Settings > Antivirus > Scans and Risks > Exclusions/Low Risks > Items to Exclude From Auto-Protect, Script Control, SONAR and Download Intelligence Detection > Configure [+] > [Add installation Directory]
3. Norton 360 > Settings > Antivirus > Automatic Protection > Auto Protect [OFF]
4. Reinstall package (no need to remove or uninstall the existing files)
5. Re-enable Auto Protect **AND** re-enable SONAR 

(Obviously, this may be different depending on your security software, but I hope this helps!)

Works like a charm, ceammc objects load as-well.

**Comment by uliss** [comment]
closing

**Comment by flarn2006** [comment]
I've experienced this problem as well and I don't use Norton

**Comment by uliss** [comment]
Did you try the latest release?

**Comment by uliss** [comment]
> Did you try the latest release?

https://github.com/uliss/pure-data/releases/tag/v2023.02

**Comment by flarn2006** [comment]
No; that's a good point. I haven't used Pure Data for the better part of a
year. Next time I try it, I'll make sure to install the latest version, and
if I still have the problem, I'll post here again.
