### ISSUE TITLE
Documentation doubt in hoa

### ISSUE THREAD

**Issue by GiuseppePisano** [uliss/pure-data#173]
As far as I understood angles for the source position in the encoder~ object are expressed in radians but angles for the speaker position in the decoder~ are expressed in degrees. Which can be confusing for some.
However, there is no clear explanation on whether degrees/radians should be counted clockwise or counterclockwise.

So far, i have experimented that radians work counterclockwise, with π/2 corresponding to 9 'o clock. but how do angles work?
For a regular decoder of a quad system going:
1 2
4 3

do I set @offset -45 or @offset 45? or @offset 135?
This is indicated nowhere in the help file.

**Comment by 60-hz** [comment]
You might find all answers in the original tutorial files which are missing from the ceammc hoa folder, but you can download them here [https://github.com/.../tree/master/Package/Hoa/tutorials](https://github.com/CICM/HoaLibrary-PD/tree/master/Package/Hoa/tutorials?fbclid=IwAR1Wn6xRX2I8nEY4ZJqR480_NfD6LtELfrWpBeD6VN1GSAveDgOaogijJP8)

Tutorial 2 should respond to many of your questions ;)

**Comment by uliss** [comment]
<img width="1178" alt="Снимок экрана 2023-10-22 в 15 26 36" src="https://github.com/uliss/pd-ceammc/assets/350661/3a5c5020-8796-4593-a328-c176965383d8">

Original HOA documentation and Tutorials now in the new release: v2023.10
