### ISSUE TITLE
midi.file -> midi.track -> midi.event2note do not reproduce 'note off' message in midi file

### ISSUE THREAD

**Issue by dalehh** [uliss/pure-data#175]
In its current form & complying with the help file structure for playing back MIDI files it appears that note off messages (note messages with a velocity of 0) are not reproduced on file playback. This results in notes hanging indefinitely and just building up as more notes are triggered.

**Comment by uliss** [comment]
Obviously, documentation should be improved and we should add sounding example with fluid~ synth.
But if you print [midi.event2note] to Pd window, there are notes off.

Could you attach the MIDI file you have problems with?

**Comment by dalehh** [comment]
Hi - thanks for the response! I'm currently printing the event2note output to the PD window as well as using a MIDI bus monitoring tool and I can confirm that I'm only seeing note on messages, but no note off messages. 

To add context - I was previously using cyclone.seq to play my MIDI files and was getting both note on and off messages, using pd vanilla 0.52 + cyclone and ceammc. Due to compatibility issues now that I transitioned an M1 Mac the only way I could get ceammc to work was with the bundled PD + ceammc distro rather than vanilla. As cyclone requires pd 0.52, I've had to abandon it and am now trying to get midi file playback to work just using ceammc.

I've attached an example file here, but I am experiencing the lack of note off messages with all my midi files.
[vocal_harm_c2.mid.zip](https://github.com/uliss/pure-data/files/9595546/vocal_harm_c2.mid.zip)

**Comment by uliss** [comment]
Tried you file - it is valid, but uncommon: 

here is output of ``mftext``:
```
Note on, chan=4 pitch=62 vol=100
Time=2250  Note off, chan=4 pitch=62 vol=64
Time=2254  Note on, chan=4 pitch=64 vol=100
Time=5245  Note on, chan=4 pitch=60 vol=100
Time=5255  Note off, chan=4 pitch=64 vol=64
Time=5876  Note off, chan=4 pitch=60 vol=64
```

There are NoteOff messages with velocity 64.  I can fix this by forcing NoteOff velocity to 0.

**Comment by dalehh** [comment]
Interesting - I wonder why it's like that. I generated my files with Logic Pro X and I can't find any reference to controlling the note off volume. That fix would work though, thanks!

**Comment by uliss** [comment]
You can try this version:

https://disk.yandex.ru/d/FUY_9_2m89LUZA

**Comment by dalehh** [comment]
I get this when I try to run it:

**Comment by dalehh** [comment]
Is it possible to install CEAMMC as an external library on PD vanilla 0.52 or greater? I have not had success with that so far but if so, it would resolve my compatibility issues.
Thanks

**Comment by uliss** [comment]
> Is it possible to install CEAMMC as an external library on PD vanilla 0.52 or greater? I have not had success with that so far but if so, it would resolve my compatibility issues. Thanks

The new release is available at github and deken. It should work with  PureData 0.52, 0.53
https://github.com/uliss/pure-data/releases/tag/v2023.02
