### ISSUE TITLE
[snd.file] can't read some formats on Windows

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#176]
I have installed k-lite codec pack on windows10 but still can't load .mp3 or MPEG AAC audio to [snd.file].

Here is the format that are returned with @formats property:
AIFF AU AVR CAF FLAC HTK IFF MAT4 MAT5 MPC OGG PAF PVF RAW RF64 SD2 SDS SF VOC W64 WAV WAVEX WVE XI

MacOS can read / play them without problem.
Any hints?

**Comment by uliss** [comment]
mp3 format loader added into Windows at release v2023.02, so everything should work

https://github.com/uliss/pd-ceammc/releases/tag/v2023.02
