### ISSUE TITLE
[ui.number] issue with label size's property

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#178]
Label size's property of [ui.number] is linked to the value displayed in the box, and not label.

**Comment by uliss** [comment]
Fixed in new pre-release

<img width="300" alt="Снимок экрана 2022-11-24 в 11 35 27" src="https://user-images.githubusercontent.com/350661/203732854-651a3bed-5ab9-4c23-98a5-eef6bd1f0855.png">
