### ISSUE TITLE
lang.faust~ feature request: add editor as in lang.lua

### ISSUE THREAD

**Issue by njazz** [uliss/pure-data#184]

**Comment by uliss** [comment]
<img width="782" alt="Снимок экрана 2023-10-22 в 15 22 33" src="https://github.com/uliss/pd-ceammc/assets/350661/8c194737-c7f1-4438-9512-59326b9fe62b">

Done. Now Faust code can be edited with internal editor with syntax highlight. Also the Faust source code is saved inside the patch.
