### ISSUE TITLE
why use "ceammc" as pd's 'test' version? please include a new definition for pd-ceammc

### ISSUE THREAD

**Issue by porres** [uliss/pure-data#190]
hi, in https://github.com/uliss/pure-data/blob/ceammc/src/m_pd.h#L14 you have 'ceammc' as the 'test version'. This is wrong and Pd uses this for the actual test version.

You can add a new definition in your header for marking this as the pd-ceammc fork of Pd. Pd-l2ork/Purr Data does that by the way, see https://github.com/agraef/purr-data/blob/master/pd/src/m_pd.h#L17

**Comment by uliss** [comment]
this macro was used to determine under which platform *ceammc* external was build, now it's obsolete, so will be removed
