### ISSUE TITLE
GUI issues with MacOS 14.0 Sonoma

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#199]
Pd-Ceammc 2023.10 for Macos Sonoma have same issue as pd with the GUI:

https://github.com/pure-data/pure-data/issues/2105

It looks to be related to tcl... should be fixed with 8.6.13

**Comment by uliss** [comment]
Thank you for your report! New versions for mac with Tcl/Tk 8.6.13 reuploaded

**Comment by 60-hz** [comment]
Great, that's much better.

Still a minor issue with the bar "hide in runmode" option :  when switching from edit mode to runmode, user need to clic once on canvas to redraw objects on screen.

**Comment by 60-hz** [comment]
The graphic issue is annoying, but could go away if user desactivate the icon bar.

**Comment by 60-hz** [comment]
I manage to fix this issue by adding "update idletasks" command in ceammc_buttonbar-plugin.tcl, line 275:

Works very well under MacOS:

```
if {$::editmode($mytoplevel)} {
        if {$::btnbar::hide_in_runmode} {
            ::btnbar::show $mytoplevel
            update idletasks
        } {
            ::btnbar::enable $mytoplevel
        }
    } {
        if {$::btnbar::hide_in_runmode} {
            ::btnbar::hide $mytoplevel
        } {
            ::btnbar::disable $mytoplevel
        }
    }
}
```


maybe you can fix it?
