### ISSUE TITLE
snd.play~ issues

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#200]
[snd.play~] seems to refuse to play, just print done when receive a start. No error message are printed...

tried [snd.file] example without problems.

Pd-ceammc_2023.10-double-macos-10.14-x86_64.dmg
MacOs Sonoma and M1

**Comment by uliss** [comment]
Oops, it seems to be error of double precision build. Fixed and reuploaded

**Comment by 60-hz** [comment]
Tested, works so it can be closed.
