### ISSUE TITLE
[ceammc] [dispatch] subscriber not found #5249597440

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#206]
This message happen to console when closing help path of [snd.play~] while reading a file.

`[ceammc] [dispatch] subscriber not found #5249597440`

**Comment by uliss** [comment]
Actually this is not a bug, but rather annoying message, when subscribed object destroyed, but worker thread is sending notification.

**Comment by uliss** [comment]
this should be fixed in the upcoming release
