### ISSUE TITLE
CEAMMC Pd library?

### ISSUE THREAD

**Issue by porres** [uliss/pure-data#25]
howdy, the readme starts by describing the project as "CEAMMC Pd library", or this at least seems to be the titled or the main thing about this project...

but it is not!

the actual project is a Pd fork, which has distinct qualities, and that also happens to include and integrate with the "CEAMMC library" 

so i think the project description is misleading

and I wonder if you have plans to actually provide a github for the "CEAMMC Pd library" itself, to be included in Pd vanilla.

thanks

**Comment by njazz** [comment]
Hello!

yes, actually it started as "library" and we are expecting to make it as a library in near future. probably will make the readme here a little bit more clear

thanks!
Alex

**Comment by uliss** [comment]
@porres - done in current release. Now this github project - the PureData distribution itself, though it includes CEAMMC library.

We plan to completely separate it, hope, to next release
