### ISSUE TITLE
Error with completion-plugin.tcl

### ISSUE THREAD

**Issue by paolopastorino** [uliss/pure-data#30]
Hi, here the error.

![schermata 2017-02-17 alle 17 26 17](https://cloud.githubusercontent.com/assets/20167693/23073877/30ccda40-f537-11e6-91f7-ca49a655d60a.png)

**Comment by uliss** [comment]
Thank you for feedback! Which system version do you have?

**Comment by paolopastorino** [comment]
I'm using osx 10.8.5.

**Comment by uliss** [comment]
@paolopastorino , could you try this build:

https://www.dropbox.com/s/fvdbn36rdk3l4gn/Pd_ceammc_2017.02_10.8_v1.dmg?dl=0

**Comment by paolopastorino** [comment]
Dear Serge,

Does not work.


Il giorno 22/feb/2017, alle ore 13:07, Serge Poltavski <notifications@github.com> ha scritto:

**Comment by uliss** [comment]
Hello, Paolo!

Could you try this build?
https://yadi.sk/d/kp5CnJ9r3FpLp4

**Comment by paolopastorino** [comment]
Hi Serge,

It seems ok.
Thank you so much!


Il giorno 14/mar/2017, alle ore 21:27, Serge Poltavski <notifications@github.com> ha scritto:
