### ISSUE TITLE
Audio operators objects bug

### ISSUE THREAD

**Issue by mrpropre** [uliss/pure-data#43]
[ui.spectroscope~] display nothing in OSX 10.9.5 and Pd-ceammc_2017.05

**Comment by uliss** [comment]
can't reproduce. which samplerate are you using?

**Comment by mrpropre** [comment]
Sorry, my mistake. [ui.spectroscope~] object  works well, title edited.

Checking  deeper in [ui.spectroscope~] helpfile, I understand the problem: [*~] second inlet is not working as it should and have a strange behaviour.

1-When sending number "1" with [toggle] in second inlet, no signal pass trough the box.
2- Going to Edition mode and resizing the [*~] box with the mouse reconnect [toggle] to first inlet!
3- Sending number "0" with [toggle] to first inlet, and resizing again the [*~] box with the mouse reconnect [toggle] to second inlet!

So there seems to be a bug with non signal inlets of all audio operator objets.

**Comment by uliss** [comment]
fixed in new release v2017.07
