### ISSUE TITLE
Backporting?

### ISSUE THREAD

**Issue by danomatika** [uliss/pure-data#46]
Would you be willing to allow back porting some of the improvements you've made into Pd vanilla?

I'm mainly looking at incorporating the Pd-extended sizing and styling variables, but there are a few more that would be great to have, including align to grid. I've started on a manual diff between the old extended sources for the object sizing, but didn't find everything yet. If I can work from the diffs from this fork, things could go a lot more quickly.

One issue with a back port is we would need to ask the original authors if they would be fine with relicensing what we do bring into Vanilla under Pd's BSD license instead of the GPL.

**Comment by njazz** [comment]
Hello Dan,

yes, it's a great idea to add it, thanks!!
i'll ask Serj to answer here too

the thing is that the grid and alignment in our release has a couple of issues. we added it as experimental/concept feature and probably will not develop that too much as we are moving to new GUI system
    - first: as i didn't find the way of getting the canvas size update events the grid now doesn't redraw on resize.
    - moving multiple objects with 'Align to grid' enabled is not working properly
Both can be easily fixed with deeper integration with original Vanilla code that we tried to avoid in several cases.

Regards,
Alex

**Comment by danomatika** [comment]
Cool. I saw that the grid sometimes draws over the top of previous objects.

What I would say is to give us a set of requirements you might need for an alternate GUI implementation. It is my desire to find a way to abstract the GUI draw commands, etc to allow for much easier, non-TCL integration, especially when using libpd. (IMHO we should move to a model where the Pd vanilla GUI uses libpd internally, but hat's a mother matter...)

I think a lot of the things people have a need to fork vanilla for could be remedied by some code layers and overridable C files. In looking a bit at the work you've done, I could see g_draw.c as a generic implementation which could be replaced/overridden, etc.

**Comment by njazz** [comment]
Ah, yes, that's the third issue with the grid :)

    And yet another issue with the grid - the performance. It's quite fine on fast machines but as it is made now in our build, it sends separate commands to draw each line. The better way of doing that would be to write tcl/tk scripts for that - and again, we tried to avoid that intentionally

     Absolutely agree with your point - we started another project as development of our build following some of these ideas. But it is yet in very early stage and there is just a screenshot and 'preview' build, not sure it's ready for any kind of testing. 
https://github.com/njazz/tilde
    We had made several choices for that:
- we decided to make the GUI model from scratch implementing some kind of MVC, encapsulating the puredata engine in separate library (later separate process etc) with some kind of 'client-server' architecture. 
- we would like to move to C++ in the GUI part as it may help to make easier API for some probable future extensions
- we chose Qt versus something more new for large user base and good enough portability. It offers easy integration with some stuff already made - first we added Python on 'client' side.
- we had to move away from lib_pd and we are making a new c/c++ library as we were missing all the essential things for detailed patch creation etc.
- Our idea is to try to make this as clear as possible - we want to make the code covered with tests and have the generated documentation for API, we expect to do that in that new project as well

So, speaking about the grid in Pd-vanilla, maybe the best way would be to add line-drawing code to Tcl/Tk scripts (canvas) and probably use our function for object position alignment (it's veery simple actually) and adding it in right places (when moving multiple objects)

**Comment by danomatika** [comment]
>encapsulating the puredata engine in separate library (later separate process etc) with some kind of 'client-server' architecture.

That sounds good and is what I'm thinking too, albeit in probably simpler terms. Have you seen the Purr-Data messaging spec? https://git.purrdata.net/jwilkes/purr-data#gui-messaging-specification

>we had to move away from lib_pd and we are making a new c/c++ library as we were missing all the essential things for detailed patch creation etc.

What I'm proposing is that we find a way to add the functionality you need, at least in a configurable/modular manner which is totally possible in the C core.

Pd has the problem of not enough developers and I would like to find a way to leverage this kind of work for everyone. I'm not against forks, but I am against constantly re-inventing the wheel. :)

**Comment by njazz** [comment]
> What I'm proposing is that we find a way to add the functionality you need, at least in a configurable/modular manner which is totally possible in the C core.

yes, it would be great - we have some things done in that direction and probably it would be great to merge some things together, i like that idea. 

We probably have to understand what things that we implemented are good to be included in the core and first we should clear that out for ourselves. I'll get back later with more details.

**Comment by porres** [comment]
I love where this is going :)

**Comment by porres** [comment]
this can be closed, huh?

**Comment by uliss** [comment]
> this can be closed, huh?

yes)
