### ISSUE TITLE
Нету Catch'а

### ISSUE THREAD

**Issue by honix** [uliss/pure-data#47]
Попытался собраться на линуксе [из вот этих](https://github.com/uliss/pure-data/releases/tag/v2017.07) релизных исходников. Вот такая ошибка:

```
. . .
[ 72%] Building CXX object ceammc/ext/src/tests/CMakeFiles/tests_main_lib.dir/tests_main.cpp.o
/home/honix/Downloads/pure-data-2017.07/ceammc/ext/src/tests/tests_main.cpp:15:10: фатальная ошибка: catch.hpp: Нет такого файла или каталога
 #include "catch.hpp"
          ^~~~~~~~~~~
компиляция прервана.
. . .
```
ps: помогло ручное добавление [Catch](https://github.com/philsquared/Catch) @ 2be3727.
думаю, это хорошо бы отразить в INSTALL.md или, еще лучше, тащить c его собой.

**Comment by uliss** [comment]
Тут такая проблема - github  сам создает тарболы исходников, но не включает файлы подмодулей. При сборе из **git** после `git clone` нужно вводить `git submodule init` и `git submodule update` - тогда все необходимые подмодули будут загружены

**Comment by honix** [comment]
Понятно :)
