### ISSUE TITLE
Install external library

### ISSUE THREAD

**Issue by paolopastorino** [uliss/pure-data#53]
Hello,

How can i do to install an external library?
I tried to put the external in /Applications/Pd-ceammc_2017.10.app/Contents/Resources/extra but it does not work.

Thank you in advance

**Comment by levelig** [comment]
Hello, Paolo!

Did you try ~/Library/Pd path?
Note: you can also use deken to install precompiled externals from repository

**Comment by paolopastorino** [comment]
Now it works.

But i can’t visualize the help file for each object… If i try to open help file from menu the object is opened.

Thank you
