### ISSUE TITLE
list.gen / list.each and custom data types

### ISSUE THREAD

**Issue by njazz** [uliss/pure-data#57]
currently objects like list.gen / list.each do not work properly if you create custom data type values inside the 'attached' function

current workaround is to use mlist data type with objects that support it:

<img width="738" alt="screen shot 2018-08-29 at 00 48 04" src="https://user-images.githubusercontent.com/3996302/44752932-39672200-ab25-11e8-99da-a66092211cf1.png">

**Comment by uliss** [comment]
Fixed
