### ISSUE TITLE
ui.env point lock ?

### ISSUE THREAD

**Issue by njazz** [uliss/pure-data#58]
when ui.env shows envelope that was generated as adsr (etc) the points may have vertical value (1.0) lock for A and D segments:

<img width="442" alt="screen shot 2018-08-29 at 00 50 57" src="https://user-images.githubusercontent.com/3996302/44753070-9f53a980-ab25-11e8-9419-d856266cde39.png">

and (0.0) vertical value for R segment

**Comment by uliss** [comment]
this is done via right click on selected point and choosing: toggle fixed Y 
![Снимок экрана 2020-02-14 в 23 56 56](https://user-images.githubusercontent.com/350661/74566994-d7eb7b00-4f85-11ea-8e3c-0f0a93cc966e.png)
