### ISSUE TITLE
function object right inlet doesn't accept [anything] message

### ISSUE THREAD

**Issue by njazz** [uliss/pure-data#59]
this could be useful for some patterns like that:
<img width="611" alt="screen shot 2018-08-29 at 00 55 20" src="https://user-images.githubusercontent.com/3996302/44753296-40426480-ab26-11e8-9d69-ee7f361054fa.png">

**Comment by uliss** [comment]
will be fixed in next release

![Снимок экрана 2020-09-04 в 2 13 32](https://user-images.githubusercontent.com/350661/92182387-475a8680-ee54-11ea-99ef-7f2735f06287.png)
