### ISSUE TITLE
Compiling just CEAMMC externals (ceammclib) without pure data distribution

### ISSUE THREAD

**Issue by miker2049** [uliss/pure-data#63]
Sorry if github issue is not the appropriate place to ask this...

ceammclib is available on deken for Windows and Mac, but not for linux, is there a way to compile just the ceammc externals for linux?  its unclear how to go about this looking at the source code, any direction would be much appreciated.  

thanks! :)

**Comment by uliss** [comment]
yes, you can compile it with `make ceammc` command and find binary **ceammc.pd_linux** at **ceammc/ext/src** directory

You could also use a snap build: 
`sudo snap install --edge pd-ceammc` 
`sudo snap connect pd-ceammc:alsa :alsa`

**Comment by miker2049** [comment]
thanks so much!

**Comment by sebshader** [comment]
I'm not very good at cmake, but was wondering if there might be instructions on how to compile just the ceammc library for osx somewhere? thanks
I've pulled from git and run ```submodule --init --recursive```..

I'm trying to be able to not use the ugly ttk "alt" theme on osx, without using the ceammc pd
