### ISSUE TITLE
fonts look bad

### ISSUE THREAD

**Issue by porres** [uliss/pure-data#64]
ceammc looks worse these days in my macOS 10.14.4, this is the last version from this repository

<img width="945" alt="ceammc" src="https://user-images.githubusercontent.com/5360142/57572962-fb323a00-73f7-11e9-92a6-67262e6675c8.png">

how vanilla looks: 
<img width="934" alt="vanilla" src="https://user-images.githubusercontent.com/5360142/57572968-12712780-73f8-11e9-9e51-6a67d623c886.png">

seems like an issue rendering fonts

**Comment by uliss** [comment]
thank you for report! do you have retina display?

**Comment by porres** [comment]
yup!
