### ISSUE TITLE
matrix object under windows disappears (32 and 64 bit)

### ISSUE THREAD

**Issue by metaphysician** [uliss/pure-data#66]
hi there = thanks for making this version of PD - it's one of the more good looking versions especially of 64 bit PD in Windows. but there's definitely an issue that i'm having with your UI grid/matrix object. under Windows if the object appears in a window - main window or subpatcher makes no difference - it is accessible only one time. if i minimize the window or close the subpatcher and then reopen it, result is a blank grey object that doesn't show any interaction at all. it also can sometimes mess with trying to get out of edit mode though this is not consistent. this is on Windows 10 64 bit. try the following:

create a new patch
add a ui.matrix objecgt
minimize the window
maximize the window - object cannot be interacted with

if you close and reopen the patch everything is fine but if you want to continue to interact with it it means the window or subpatcher has to stay open and never close which is not terribly convenient.

everything is fine under macOS - in fact i took my patch over to Windows where i discovered this particular weird behavior. this issue happens in vanilla PD in 32 bit and 64 bit as well as the CEAMMC distributions under Windows.

one other thing. i tried using a similar object from Alexander Porres's ELSE library, which looks like some form of vanilla patching to me. in regular PD this shows up fine but in CEAMMC PD it's basically broken. 

on the positive side your MIDI input response seems to work fine with no data latency, whereas under vanilla i'm getting 15 second pauses before the data is recognized, which is why i switched to the CEAMMC distribution to see if that would solve the issue. it solved the issue with that but the matrix glitch persists.

anyway, any tips you might offer for better UI window response for the matrix object, or fixes to the interaction and UI behavior would be helpful - thanks!

**Comment by uliss** [comment]
Thank you for your report!

**Comment by metaphysician** [comment]
thanks for checking this out! a bit more information on the problem that i found. 

when i first encountered the behavior i noticed it was on my Windows 10 laptop, which has a NVIDIA 1070 GPU. for various stability and compatibility reasons i've actually installed macOS on it, so it is now a dual boot Hackintosh/Windows laptop. and interestingly enough the problem persists even when it's running macOS instead of Windows. which means that it doesn't seem to be the OS that's the issue, but rather the GPU creating a problem. on my other Mac (a desktop Hackintosh), it has a NVIDIA 650Ti, and there are no issues with the grid object disappearing. the mac OS is High Sierra 10.13.6, same as the laptop. so this seems like more of a possible Tcl/Tk issue (assuming that's what you're using to create your custom UI objects) with how it performs with newer GPUs.

further, i can verify that even though nothing is displayed during the glitch, clicking in the area does function as before, but with no visual feedback you can only tell by sound and not by sight.

i hope that some of this information is helpful!

**Comment by uliss** [comment]
@metaphysician, could you try this build:
https://drive.google.com/open?id=1X8Bym5GOAJLUSDpnb6W3qHhQ57O5Qv1T

with this test patch it seems to work for me
[test_matrix.zip](https://github.com/uliss/pure-data/files/3443936/test_matrix.zip)

**Comment by metaphysician** [comment]
hi Serge! - this patch seems to work fine overall! if you can, please do me a favor and get me a Mac 64 bit build, this will help me the most, as i've run into audio performance issues under Windows and i'm not using it currently. this way we can also test if the fix works on the Mac. thanks in advance!

**Comment by uliss** [comment]
you can try this build:

https://drive.google.com/open?id=1VcKodOa4A2APTba54n4rqXrRUB8bMVq7
