### ISSUE TITLE
Gui objects problems on windows plateform

### ISSUE THREAD

**Issue by mrpropre** [uliss/pure-data#67]
I used pd-ceammc on OSX and everything was smooth.
But on a Windows 10 64bit machine I can't resize or move the ceammc gui objects correctly with the mouse. They looks like "stuck" in the back. I can select and move them using the keyboard though.

Is it a normal behaviour or my windows system has a failure? Maybe a tk pb?

**Comment by uliss** [comment]
do you have troubles with all gui objects, or with some of them?

**Comment by mrpropre** [comment]
All ui objects who are using the CICM wrapper I guess...

**Comment by mrpropre** [comment]
I see that the Cream Library has exactly the same behavior on this windows computer... I think the cicm wrapper might have some issues on windows. Did you ever encounter such problems on a windows 10 machine or is it my own configuration?

**Comment by mrpropre** [comment]
Here is some update:

I think the culpid might be "triggerize function".
I can get the same GUI freezing using OSX a a few steps:

1-create a new CICMM GUI object
2-create a second one
3-select the connection
4-hit "Command+T"
5-Gui is freezed.

Solution: hide the patch and show it again to make it works again.

Something might me blocking redraw in the CICM wrapper after a "triggerize" function.
But in windows the GUI is always frozen for me, maybe another bug?

**Comment by uliss** [comment]
Thank you for your verbose report. Seems I found the reason.

**Comment by mrpropre** [comment]
Will you make a release soon so that Windows user can use it?
