### ISSUE TITLE
Trying to compile pd-ceammc and ceammclib for Raspbian-stretch

### ISSUE THREAD

**Issue by ghost** [uliss/pure-data#68]
Hi there,
I'm trying to compile the latest released version of pd-ceammc and its library, for Raspbian-stretch on Raspberry Pi. I followed all your instructions in the "INSTALL.txt" file, but when I launch the ./autogen.sh script, I get the following error message :

[autogen.log](https://github.com/uliss/pure-data/files/3723711/autogen.log)

Can you please help us with the compiling process on Linux / Raspberry Pi ?

Best,

WoollyB

**Comment by AurelienConil** [comment]
`sudo apt install libtool` works for me.
But still crashing during the building part

**Comment by uliss** [comment]
we are using cmake build system.

Here's short manual 
https://github.com/uliss/pure-data/wiki/Build-from-sources

**Comment by AurelienConil** [comment]
It gave me an error at cmake commande line.
Maybe because I use special raspbian with real-time kernel ?
`CMake Error at /usr/share/cmake-3.13/Modules/CMakeCompilerIdDetection.cmake:110 (message): No preprocessor test for "zOS"`

**Comment by uliss** [comment]
Which compiler are you using? gcc or clang? Could you paste all cmake output?

**Comment by AurelienConil** [comment]
Previously, I tried with a special real-time kernel version of Raspbian called [PatchboxOS](https://blokas.io/patchbox-os/). It failed with my previous message.
I tried yesterday with the last version of raspbian, using CMake. It was defitively better, but it failed at 99% :
```
[ 99%] Built target test_ext_wrapper
Scanning dependencies of target matrix
[ 99%] Building CXX object ceammc/ext/class-wrapper/CMakeFiles/matrix.dir/modules/matrix/gen_matrix.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [ceammc/ext/tests/ui/CMakeFiles/test_ext_ui.dir/build.make:336: ceammc/ext/tests/ui/CMakeFiles/test_ext_ui.dir/test_ui_polar.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:16930: ceammc/ext/tests/ui/CMakeFiles/test_ext_ui.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 99%] Linking CXX shared library matrix.pd_linux
[ 99%] Built target matrix
make: *** [Makefile:163: all] Error 2
```

**Comment by AurelienConil** [comment]
Hello . Finnaly I used a standard version of Raspbian, and succefully compiled pd-ceammc.
I get the deb file, and installed it ( I can share the link if you want ).
I had to add mannually a .so library file that was not copied ( inside /usr/lib/pd_ceammc ... ), but at least it work.

I will try now to install the .deb file inside the Patchbox OS

**Comment by uliss** [comment]
> Previously, I tried with a special real-time kernel version of Raspbian called [PatchboxOS](https://blokas.io/patchbox-os/). It failed with my previous message.
> I tried yesterday with the last version of raspbian, using CMake. It was defitively better, but it failed at 99% :
> 
> ```
> [ 99%] Built target test_ext_wrapper
> Scanning dependencies of target matrix
> [ 99%] Building CXX object ceammc/ext/class-wrapper/CMakeFiles/matrix.dir/modules/matrix/gen_matrix.cpp.o
> c++: fatal error: Killed signal terminated program cc1plus
> compilation terminated.
> make[2]: *** [ceammc/ext/tests/ui/CMakeFiles/test_ext_ui.dir/build.make:336: ceammc/ext/tests/ui/CMakeFiles/test_ext_ui.dir/test_ui_polar.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:16930: ceammc/ext/tests/ui/CMakeFiles/test_ext_ui.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 99%] Linking CXX shared library matrix.pd_linux
> [ 99%] Built target matrix
> make: *** [Makefile:163: all] Error 2
> ```

this error probably because if heavy template usage in matrix and numeric externals and gcc goes out of memory.

**Comment by uliss** [comment]
> Hello . Finnaly I used a standard version of Raspbian, and succefully compiled pd-ceammc.
> I get the deb file, and installed it ( I can share the link if you want ).
> I had to add mannually a .so library file that was not copied ( inside /usr/lib/pd_ceammc ... ), but at least it work.
> 
> I will try now to install the .deb file inside the Patchbox OS

By default cmake install prefix is **/usr/local**. You can change to **/usr** it with cmake configure option:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr ....
```

then rebuild, make deb and install it with dpkg

**Comment by uliss** [comment]
close due lack of activity
