### ISSUE TITLE
button bar don´t work on windows 7 32 bits

### ISSUE THREAD

**Issue by aclaiman** [uliss/pure-data#69]
Hi,
This is the message in the console.
I have installed the pd ceaamc 2020.02

Thanks

`-----------
UNHANDLED ERROR: can't find package base64
    while executing
"package require base64"
    ("uplevel" body line 8)
    invoked from within
"uplevel #0 $tclcode"
FAILED TO LOAD C:/Program Files/PureData CEAMMC/tcl/ceammc/ceammc_buttonbar-plugin.tcl
-----------`

**Comment by uliss** [comment]
uploaded new 32-bit version. could you try it?

**Comment by aclaiman** [comment]
Works great with this new version!
Thanks!
Regards from Argentina!

**Comment by aclaiman** [comment]
Works great with this new version!
Thanks!
Regards from Argentina!
