### ISSUE TITLE
compiling from source on linux 32 bits

### ISSUE THREAD

**Issue by AurelienConil** [uliss/pure-data#75]
Hello
I get bloked on compiling pd-ceammc on linux 32 bit ( mint 19.3 ), on the CMAKE step.
While calling the cmakelists in ceammc/ext/src/lib/CMakeLists.txt,  I received this message
` You have called ADD_LIBRARY for library ceammc_core without any source files. This typically indicates a problem with your CMakeLists.txt file `
I tried to print ceammc_core and it is empty.
Where it is supposed to be setted ?  How i can solve it ?

Probably on conclusion of this, i received all the xcb module not found :
`
Could NOT find XCB_XFIXES (missing: XCB_XFIXES_LIBRARY XCB_XFIXES_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_COMPOSITE (missing: XCB_COMPOSITE_LIBRARY XCB_COMPOSITE_INCLUDE_DIR XCB_XFIXES_FOUND) (found version "")
-- Could NOT find XCB_CURSOR (missing: XCB_CURSOR_LIBRARY XCB_CURSOR_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_DAMAGE (missing: XCB_DAMAGE_LIBRARY XCB_DAMAGE_INCLUDE_DIR XCB_XFIXES_FOUND) (found version "")
`
etc...

Thanks

**Comment by uliss** [comment]
- It should be just a cmake warning message. I suppose that cmake failed by another reason. Could you post the full cmake output?

- you don't have libxcb*-dev files installed, so it seems to be a reason. But again it should be only a warning message, not an error.

**Comment by uliss** [comment]
close due lack of activity and cmake fixes
