### ISSUE TITLE
[string.remove] type error

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#76]
When opening the help file, trow this errors into the console:

[string.remove] [@str] symbol expected, got 123
[string.remove] can't set property: @str
[string.remove] [@str] symbol expected, got 123
[string.remove] can't set property: @str
[string.remove] [@str] symbol expected, got 123
[string.remove] can't set property: @str
You need some valid buffers

The exemple use numbers and string.remove cannot understand numbers as string.

library: ceammc v0.9.0 & PureData distribution v2020.07

**Comment by uliss** [comment]
will be fixed in next release.

To use string.remove with numbers as symbols you should use double quotes: [string.remove "123"]

![Снимок экрана 2020-09-04 в 0 03 58](https://user-images.githubusercontent.com/350661/92167288-d068c200-ee42-11ea-9cb8-e6f6670fa447.png)
