### ISSUE TITLE
toolbar fails to load on windows

### ISSUE THREAD

**Issue by njazz** [uliss/pure-data#82]
on Windows 8 in current build:
tcl error:
UNHANDLED ERROR: can't find package tooltip wile executing
'package require tooltip' ("uplevel" body line 10)
invoked from within "uplevel #0 $tclcode"
FAILED TO LOAD C:/Program Files/PureData CEAMMC/tcl/ceammc/ceammc_buttonbar-plugin.tcl

**Comment by uliss** [comment]
seems to be fixed in recent release
